import type { Metadata } from 'next'
import '@/styles/globals.css'
import { geistSans, geistMono } from '@/styles/fonts'
import Providers from '@/providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modals,
}: Readonly<{
  children: React.ReactNode
  modals: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
          {modals}
        </Providers>
      </body>
    </html>
  )
}
