-- AlterTable
ALTER TABLE "Node" ADD COLUMN     "parentNodeId" TEXT,
ADD COLUMN     "positionX" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "positionY" DOUBLE PRECISION NOT NULL DEFAULT 0.0;

-- AddForeignKey
ALTER TABLE "Node" ADD CONSTRAINT "Node_parentNodeId_fkey" FOREIGN KEY ("parentNodeId") REFERENCES "Node"("id") ON DELETE SET NULL ON UPDATE CASCADE;
